# Uncomment the next line to define a global platform for your project
platform :osx, '10.11'

target 'StringUtility' do
  pod 'NVHTarGzip', :git => 'https://github.com/konkab/NVHTarGzip'
  pod 'TMLKit', :path => '/Users/konstantinkabanov/Repositories/tml-objc'
end
